### PR TITLE
Park layout updates

### PR DESCRIPTION
**Pull request by siva-ka**
# Description

This PR includes the following proposed change(s):

- BC-510

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Does the change impact or break the Docker build?

- [ ] Yes
- [ ] No

If Yes: Has Docker been updated accordingly?

- [ ] Yes
- [ ] No

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by BenHarrington — APPROVED** [review]

**Review by BcGovNeal — CHANGES_REQUESTED** [review]
Build is failing with

```
warn Plugin gatsby-plugin-sass is not compatible with your gatsby version 3.13.1 - It requires gatsby@^2.0.0
warn Plugin gatsby-plugin-sass is not compatible with your gatsby version 3.13.1 - It requires gatsby@^2.0.0
success open and validate gatsby-configs, load plugins - 0.437s
success onPreInit - 0.029s
success initialize cache - 0.013s
success copy gatsby files - 0.090s
success Compiling Gatsby Functions - 0.111s
success onPreBootstrap - 0.121s
success createSchemaCustomization - 0.016s
info Starting to fetch data from Strapi - http://localhost:1337/urgencies with params {"_limit":-1}
info Starting to fetch data from Strapi - http://localhost:1337/protected-areas with params {"_limit":-1}
info Starting to fetch data from Strapi - http://localhost:1337/public-advisories with params {"_limit":-1}
info Starting to fetch data from Strapi - http://localhost:1337/park-access-statuses with params {"_limit":-1}
info Starting to fetch data from Strapi - http://localhost:1337/park-photos with params {"_limit":-1}
info Starting to fetch data from Strapi - http://localhost:1337/Websites with params {"_limit":-1}
info Starting to fetch data from Strapi - http://localhost:1337/Pages with params {"_limit":-1}
info Starting to fetch data from Strapi - http://localhost:1337/activity-types with params {"_limit":-1}
info Starting to fetch data from Strapi - http://localhost:1337/facility-types with params {"_limit":-1}
success Fetched Strapi Data - 5.732s
success Checking for changed pages - 0.001s
success source and transform nodes - 6.187s
success building schema - 0.792s
success createPages - 0.205s
success createPagesStatefully - 0.054s
info Total nodes: 4012, SitePage nodes: 1044 (use --verbose for breakdown)
success Checking for changed pages - 0.001s
success update schema - 0.084s
success onPreExtractQueries - 0.001s
success extract queries from components - 1.081s
success write out redirect data - 0.002s
success Build manifest and related icons - 0.037s
success onPostBootstrap - 0.041s
info bootstrap finished - 10.571s
success run static queries - 0.009s - 2/2 211.24/s
success run page queries - 5.876s - 1044/1044 177.68/s
success write out requires - 0.012s
warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:23294: TypeError: Cannot read property 'includes' of undefined
warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:24339: TypeError: Cannot read property 'includes' of undefined
warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:24339: TypeError: Cannot read property 'includes' of undefined
warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:27840: TypeError: Cannot read property 'includes' of undefined
warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:28955: TypeError: Cannot read property 'includes' of undefined
warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:28955: TypeError: Cannot read property 'includes' of undefined
warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:62813: TypeError: Cannot read property 'includes' of undefined
warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:63233: TypeError: Cannot read property 'includes' of undefined
warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:63780: TypeError: Cannot read property 'includes' of undefined
warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:65422: TypeError: Cannot read property 'includes' of undefined
warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:76821: TypeError: Cannot read property 'includes' of undefined
warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:77889: TypeError: Cannot read property 'includes' of undefined
warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:108628: TypeError: Cannot read property 'includes' of undefined
warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:108851: TypeError: Cannot read property 'includes' of undefined
success Building production JavaScript and CSS bundles - 127.390s
success Rewriting compilation hashes - 0.014s
success Writing page-data.json files to public directory - 0.926s - 1044/1044 1127.63/s
success Building HTML renderer - 14.320s
failed Building static HTML for pages - 1.195s

 ERROR #95313 

Building static HTML failed

See our docs page for more info on this error: https://gatsby.dev/debug-html


  3 | See https://js.arcgis.com/4.20/esri/copyright.txt for details.
  4 | */
> 5 | function e(e){return"string"==typeof e?document.getElementById(e):e}function t(e){for(;e.hasChildNodes();)e.removeChild(e.firstChild)}function n(e,t){const
n=t.parentNode;n&&(n.lastChild===t?n.appendChild(e):n.insertBefore(e,t.nextSibling))}function o(e,t){const n=t.parentNode;n&&n.insertBefore(e,t)}function r(e,t){for(;;){const n=e.firstChild;if(!n)break;t.appendChild(n)}}function
i(e){e.parentNode&&e.parentNode.removeChild(e)}const l=(()=>{if("function"==typeof Element.prototype.closest)return(e,t)=>e.closest(t);const e=Element.prototype.matches||Element.prototype.msMatchesSelector;return(t,n)=>{let
o=t;do{if(e.call(o,n))return o;o=o.parentElement}while(null!==o&&1===o.nodeType);return null}})();export{e as byId,l as closest,t as empty,n as insertAfter,o as insertBefore,i as remove,r as reparent};
    |
                                                                                                                                                                                                            ^
  6 |


  WebpackError: ReferenceError: Element is not defined
  
  - domUtils.js:5 
    [bc-parks-staging]/[@arcgis]/core/core/domUtils.js:5:447
  
  - domUtils.js:5 
    [bc-parks-staging]/[@arcgis]/core/core/domUtils.js:5:704
  
  - bootstrap:19 
    bc-parks-staging/webpack/bootstrap:19:1
  
  - bootstrap:19 
    bc-parks-staging/webpack/bootstrap:19:1
  
  - bootstrap:19 
    bc-parks-staging/webpack/bootstrap:19:1
  
  - bootstrap:19 
    bc-parks-staging/webpack/bootstrap:19:1
  
  - bootstrap:19 
    bc-parks-staging/webpack/bootstrap:19:1
  
  - sync-requires.js:14 
    bc-parks-staging/.cache/_this_is_virtual_fs_path_/$virtual/sync-requires.js:14:63
  
  - bootstrap:19 
    bc-parks-staging/webpack/bootstrap:19:1
  
  - static-entry.js:15 
    bc-parks-staging/.cache/static-entry.js:15:22
  

not finished Caching JavaScript and CSS webpack compilation - 22.220s
not finished Caching HTML renderer compilation - 1.424s
```

**Comment by siva-ka** [comment]
> Build is failing with
> 
> ```
> warn Plugin gatsby-plugin-sass is not compatible with your gatsby version 3.13.1 - It requires gatsby@^2.0.0
> warn Plugin gatsby-plugin-sass is not compatible with your gatsby version 3.13.1 - It requires gatsby@^2.0.0
> success open and validate gatsby-configs, load plugins - 0.437s
> success onPreInit - 0.029s
> success initialize cache - 0.013s
> success copy gatsby files - 0.090s
> success Compiling Gatsby Functions - 0.111s
> success onPreBootstrap - 0.121s
> success createSchemaCustomization - 0.016s
> info Starting to fetch data from Strapi - http://localhost:1337/urgencies with params {"_limit":-1}
> info Starting to fetch data from Strapi - http://localhost:1337/protected-areas with params {"_limit":-1}
> info Starting to fetch data from Strapi - http://localhost:1337/public-advisories with params {"_limit":-1}
> info Starting to fetch data from Strapi - http://localhost:1337/park-access-statuses with params {"_limit":-1}
> info Starting to fetch data from Strapi - http://localhost:1337/park-photos with params {"_limit":-1}
> info Starting to fetch data from Strapi - http://localhost:1337/Websites with params {"_limit":-1}
> info Starting to fetch data from Strapi - http://localhost:1337/Pages with params {"_limit":-1}
> info Starting to fetch data from Strapi - http://localhost:1337/activity-types with params {"_limit":-1}
> info Starting to fetch data from Strapi - http://localhost:1337/facility-types with params {"_limit":-1}
> success Fetched Strapi Data - 5.732s
> success Checking for changed pages - 0.001s
> success source and transform nodes - 6.187s
> success building schema - 0.792s
> success createPages - 0.205s
> success createPagesStatefully - 0.054s
> info Total nodes: 4012, SitePage nodes: 1044 (use --verbose for breakdown)
> success Checking for changed pages - 0.001s
> success update schema - 0.084s
> success onPreExtractQueries - 0.001s
> success extract queries from components - 1.081s
> success write out redirect data - 0.002s
> success Build manifest and related icons - 0.037s
> success onPostBootstrap - 0.041s
> info bootstrap finished - 10.571s
> success run static queries - 0.009s - 2/2 211.24/s
> success run page queries - 5.876s - 1044/1044 177.68/s
> success write out requires - 0.012s
> warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:23294: TypeError: Cannot read property 'includes' of undefined
> warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:24339: TypeError: Cannot read property 'includes' of undefined
> warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:24339: TypeError: Cannot read property 'includes' of undefined
> warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:27840: TypeError: Cannot read property 'includes' of undefined
> warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:28955: TypeError: Cannot read property 'includes' of undefined
> warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:28955: TypeError: Cannot read property 'includes' of undefined
> warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:62813: TypeError: Cannot read property 'includes' of undefined
> warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:63233: TypeError: Cannot read property 'includes' of undefined
> warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:63780: TypeError: Cannot read property 'includes' of undefined
> warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:65422: TypeError: Cannot read property 'includes' of undefined
> warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:76821: TypeError: Cannot read property 'includes' of undefined
> warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:77889: TypeError: Cannot read property 'includes' of undefined
> warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:108628: TypeError: Cannot read property 'includes' of undefined
> warn Css Minimizer Plugin: postcss-svgo: /home/nli/bcgov/bcparks/bcparks.ca/src/staging/styles.432cada7538c2016d226.css:9:108851: TypeError: Cannot read property 'includes' of undefined
> success Building production JavaScript and CSS bundles - 127.390s
> success Rewriting compilation hashes - 0.014s
> success Writing page-data.json files to public directory - 0.926s - 1044/1044 1127.63/s
> success Building HTML renderer - 14.320s
> failed Building static HTML for pages - 1.195s
> 
>  ERROR #95313 
> 
> Building static HTML failed
> 
> See our docs page for more info on this error: https://gatsby.dev/debug-html
> 
> 
>   3 | See https://js.arcgis.com/4.20/esri/copyright.txt for details.
>   4 | */
> > 5 | function e(e){return"string"==typeof e?document.getElementById(e):e}function t(e){for(;e.hasChildNodes();)e.removeChild(e.firstChild)}function n(e,t){const
> n=t.parentNode;n&&(n.lastChild===t?n.appendChild(e):n.insertBefore(e,t.nextSibling))}function o(e,t){const n=t.parentNode;n&&n.insertBefore(e,t)}function r(e,t){for(;;){const n=e.firstChild;if(!n)break;t.appendChild(n)}}function
> i(e){e.parentNode&&e.parentNode.removeChild(e)}const l=(()=>{if("function"==typeof Element.prototype.closest)return(e,t)=>e.closest(t);const e=Element.prototype.matches||Element.prototype.msMatchesSelector;return(t,n)=>{let
> o=t;do{if(e.call(o,n))return o;o=o.parentElement}while(null!==o&&1===o.nodeType);return null}})();export{e as byId,l as closest,t as empty,n as insertAfter,o as insertBefore,i as remove,r as reparent};
>     |
>                                                                                                                                                                                                             ^
>   6 |
> 
> 
>   WebpackError: ReferenceError: Element is not defined
>   
>   - domUtils.js:5 
>     [bc-parks-staging]/[@arcgis]/core/core/domUtils.js:5:447
>   
>   - domUtils.js:5 
>     [bc-parks-staging]/[@arcgis]/core/core/domUtils.js:5:704
>   
>   - bootstrap:19 
>     bc-parks-staging/webpack/bootstrap:19:1
>   
>   - bootstrap:19 
>     bc-parks-staging/webpack/bootstrap:19:1
>   
>   - bootstrap:19 
>     bc-parks-staging/webpack/bootstrap:19:1
>   
>   - bootstrap:19 
>     bc-parks-staging/webpack/bootstrap:19:1
>   
>   - bootstrap:19 
>     bc-parks-staging/webpack/bootstrap:19:1
>   
>   - sync-requires.js:14 
>     bc-parks-staging/.cache/_this_is_virtual_fs_path_/$virtual/sync-requires.js:14:63
>   
>   - bootstrap:19 
>     bc-parks-staging/webpack/bootstrap:19:1
>   
>   - static-entry.js:15 
>     bc-parks-staging/.cache/static-entry.js:15:22
>   
> 
> not finished Caching JavaScript and CSS webpack compilation - 22.220s
> not finished Caching HTML renderer compilation - 1.424s
> ```

Merged latest code to branch to fix build issues

**Comment by siva-ka** [comment]
> Please fix the following:
> 
> ```
> Warning: Invalid DOM property `class`. Did you mean `className`?
> Warning: Failed prop type: The prop `xs` of `Grid` must be used on `item`.
> ```
> 
> Also I'm seeing some icons missing on the parks page. `ATVing` and `RV-Accessible Camping` are just 2 that I noticed, there could be others. Is this intended?

I have fixed the console logs. One of the "className" warning comes from a library, hence I am unable to fix it. Some icons are missing in the CMS, its a data issue.

**Review by BcGovNeal — APPROVED** [review]
Looks good.  Thanks for the fixes

**Review by BenHarrington — APPROVED** [review]

**Pull request merged**
