### PR TITLE
CM-410: Add page scroll useEffect

### PR DESCRIPTION
**Pull request by ayumi-oxd**
### Jira Ticket:
CM-410

### Jira Ticket URL:
https://bcparksdigital.atlassian.net/browse/CM-410

### Description:
- Made the find-a-park page scroll to the top every time the pagination clicked

### CODE REVIEW

**Comment by molund** [comment]
Please see the comment I added to the ticket.

**Comment by ayumi-oxd** [comment]
- Changed the scroll position

**Comment by nataliasabadysh** [comment]
does not scroll to the top of the page (including the Headline, Header, and so on)
just to TextField with the ref 

image

if we need to the Top Page 
you could use this method, this takes position to the viewport
 

`  const handlePageChange = (event, value) => {
    setCurrentPage(value)
    const dims = searchRef.current.getBoundingClientRect();
    window.scrollTo({
      behavior: 'smooth',
      top: dims.top,
    });
  }`

**Comment by ayumi-oxd** [comment]
> does not scroll to the top of the page (including the Headline, Header, and so on) just to TextField with the ref
> 
> image
> 
> if we need to the Top Page you could use this method, this takes position to the viewport
> 
> ```
> const handlePageChange = (event, value) => {
>     setCurrentPage(value)
>     const dims = searchRef.current.getBoundingClientRect();
>     window.scrollTo({
>       behavior: 'smooth',
>       top: dims.top,
>     });
>   }
> ```

Oh, I changed the position based on the feedback from Jane and Mike 🙂 Details are in [this ticket](https://bcparksdigital.atlassian.net/browse/CM-410).

**Comment by foley-lynn** [comment]
This isn't working reliably for Safari and Firefox.

**Comment by ayumi-oxd** [comment]
> This isn't working reliably for Safari and Firefox.

Good catch, thanks! Seems there are some differences in `scrollIntoView` between browsers. 
Added polyfill and works fine on any browser.

**Review by foley-lynn — APPROVED** [review]

**Review by molund — APPROVED** [review]

**Review by nataliasabadysh — APPROVED** [review]

**Pull request merged**
