### PR TITLE
CM-244: Format the park operations section

### PR DESCRIPTION
**Pull request by molund**
### Jira Ticket:
CM-244

### Jira Ticket URL:
https://bcparksdigital.atlassian.net/browse/CM-244

### Description:
Format the "Dates of operation" section on Parks pages according to wireframes in the ticket

### CODE REVIEW

**Review by foley-lynn — APPROVED** [review]

**Comment by foley-lynn** [comment]
This looks really good Mike. Nice work.

**Comment by ayumi-oxd** [comment]
One question - I was at `/adams-lake-bush-creek-site-park/` with PROD data. I see "Open to public access May 13, 2022 to September 15, 2022" under the Dates of operation, but it's supposed to be not displayed based on Jane's notes in the wireframe. Sorry if I missed something 😅

Other than that it looks great 👏

**Comment by molund** [comment]
@ayumi-oxd 
I'm was expecting that once I refresh the park operation data with 2023 information, the dates for Adams Lake Bush Creek Site would be 2023 dates.  However, I checked prod and I noticed that this park currently has no operating dates section at all.....
https://bcparks.ca/explore/parkpgs/adams_lk_bush_crk/
I wonder if maybe the preferred fallback behaviour in January is to hide the entire "Dates of Operation" section instead of showing last year's dates?

**Comment by ayumi-oxd** [comment]
@molund That fallback sounds right to me 🙂 But also I'm concerned we wouldn't have the Dates of operation on any park pages until `ParkOperations` data is updated from 2022 to 2023. At this moment, I don't see [any data that starts or ends in 2023](https://cms.bcparks.ca/admin/plugins/content-manager/collectionType/application::park-operation.park-operation?page=1&pageSize=10&_sort=openDate:DESC). Talking to Jane about this might be a good idea.

**Comment by molund** [comment]
@ayumi-oxd I asked Leah, and she wanted to change the fallback.  Now if the dates are missing we will still show the section, but instead of dates it will say "Operating dates are not yet available".  In addition, the accordion sections will now appear when there are no dates as well.  But under "Main season camping dates" it will say "2023: Dates are not yet available".
image (3)

**Review by ayumi-oxd — APPROVED** [review]
I was able to check the new fallback on my local, and it looks awesome 👏

**Comment by ayumi-oxd** [comment]
@molund Sorry one nitpicking 😅 If you could change `class` to `className`, it would be more awesome!

**Comment by molund** [comment]
Done.  Good catch!  Can you tell they never let me do front-end work in React? 😄

**Pull request merged**
