### PR TITLE
CMS-400: Fix the issue when navigating page section directly from a url

### PR DESCRIPTION
**Pull request by ayumi-oxd**
### Jira Ticket:
CMS-400

### Description:
- Fix the issue when navigating page section directly from a url
- I'm not 100% sure if it'll fix it since I couldn't recreate it on my local 🤔 Just applied the change based on their doc: https://www.npmjs.com/package/react-use-scrollspy

### CODE REVIEW

**Comment by duncan-oxd** [comment]
From the video Manuji posted in the ticket, it looks like the browser doesn't quite scroll far enough to trigger the "Contact" section being highlighted. (I would expect it to scroll "Contact" to the top of the screen, but it stops half way up the page. It might be related to React Router, or: is there any special code that handles that scrolling to specific page sections?

**Comment by ayumi-oxd** [comment]
> From the video Manuji posted in the ticket, it looks like the browser doesn't quite scroll far enough to trigger the "Contact" section being highlighted. (I would expect it to scroll "Contact" to the top of the screen, but it stops half way up the page. It might be related to React Router, or: is there any special code that handles that scrolling to specific page sections?

We have this scroll in `useEffect`,
```
  useEffect(() => {
    if (window.location.hash && !isLoadingProtectedArea && !isLoadingAdvisories) {
      const id = window.location.hash.replace("#", "")
      const element = document.getElementById(id) || document.querySelector(window.location.hash)
      if (element) {
        element.scrollIntoView({ behavior: 'smooth', block: 'start' })
      }
    }
  }, [isLoadingProtectedArea, isLoadingAdvisories])
```
And this `useScrollSpy` to highlight the side menu based on the scroll position.
```
  const activeSection = useScrollSpy({
    sectionElementRefs: sectionRefs,
    defaultValue: 0,
    offsetPx: -100,
  })
```
So I might need to take a look at `useEffect` part more. The tricky part is that I couldn't recreate it locally 😅

**Comment by duncan-oxd** [comment]
> So I might need to take a look at `useEffect` part more. The tricky part is that I couldn't recreate it locally 😅

Chrome seems unreliable with scrollIntoView when a page is loading or an element is just mounting. I noticed this a lot on previous projects. I hate to say it, but the only solution at the time was to pause for a few milliseconds, or run scrollIntoView twice. Both ways felt like bad hacks :( Let me know if you find a cleaner solution!

**Review by duncan-oxd — APPROVED** [review]
Hopefully the setTimeout is enough to make it work reliably enough for most users!

**Pull request merged**
