### PR TITLE
CM-905: Use sections for region filters

### PR DESCRIPTION
**Pull request by molund**
### Jira Ticket:

- CM-903
- CM-904
- CM-905
- CM-916

### Description:

- Front-end and back-end implementation for searching by sections (now called search-areas)
- Renamed the Search-region collection type to Search-area as per UX feedback (change to #953)
- Renamed all references to "region" in search code to use "area" instead
- Updated the Elasticsearch indexer to index search-area for parks
- CM-916: When a park is in multiple sections, list all sections (i.e. Tweedsmuir and Strathcona) 
- Removed some unused Gatsby GraphQL collections
- Fixed a bug where checked filters couldn't be unchecked if they had zero results

NOTE: You will need to run this SQL command after you deploy this change because Strapi run migration before the automated schema migrations that Strapi also performs on boot. 
```
delete from strapi_migrations where name = '2023.08.31T00.00.07.search-area.js';
```

After running this command and restarting Strapi, you will also need to re-index Elasticsearch
```
node index.js reindex
```

### CODE REVIEW

**Review by ayumi-oxd — COMMENTED** [review]
Gatsby build failed:
```
ERROR #85923  GRAPHQL.VALIDATION

There was an error in your GraphQL query:

Cannot query field "allStrapiSearchArea" on type "Query".

If you don't expect "allStrapiSearchArea" to exist on the type "Query"
 it is most likely a typo. However, if you expect
"allStrapiSearchArea" to exist there are a couple of solutions to
common problems:

- If you added a new data source and/or changed something inside
gatsby-node/gatsby-config, please try a restart of your development
server.
- You want to optionally use your field "allStrapiSearchArea" and
right now it is not used anywhere.

It is recommended to explicitly type your GraphQL schema if you want
to use optional fields.

File: src/pages/find-a-park.js:40:5

See our docs page for more info on this error:
https://gatsby.dev/creating-type-definitions

failed extract queries from components - 2.367s
```

**Comment by molund** [comment]
@ayumi-oxd can please you try setting permissions on the Search-area collection type in the Strapi back-end?

**public role**:  find and findOne
**authenticated role**:  all permissions

Let me know if that fixes it.  I think I was getting the same error until I set these.

> Gatsby build failed:
> 
> ```
> ERROR #85923  GRAPHQL.VALIDATION
> 
> There was an error in your GraphQL query:
> 
> Cannot query field "allStrapiSearchArea" on type "Query".

**Comment by ayumi-oxd** [comment]
> @ayumi-oxd can please you try setting permissions on the Search-area collection type in the Strapi back-end?
> 
> **public role**: find and findOne **authenticated role**: all permissions
> 
> Let me know if that fixes it. I think I was getting the same error until I set these.
> 
> > Gatsby build failed:
> > ```
> > ERROR #85923  GRAPHQL.VALIDATION
> > 
> > There was an error in your GraphQL query:
> > 
> > Cannot query field "allStrapiSearchArea" on type "Query".
> > ```

@molund Unfortunately, I'm still having the same GraphQL error.

**Review by ayumi-oxd — APPROVED** [review]
LGTM 👍 Filtering parks by area works as expected on laptop/mobile.

**Pull request merged**
