### PR TITLE
Keycloak strapi

### PR DESCRIPTION
**Pull request by cameronpettit**
# Description

This PR includes the following proposed change(s):

- BC-497 https://bcdevex.atlassian.net/jira/software/projects/BC/boards/6/backlog?selectedIssue=BC-489 "Protect Data in Strapi"

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

### CODE REVIEW

**Review by BcGovNeal — DISMISSED** [review]

**Review by nileshnad — COMMENTED** [review]
Are there any setup instructions for this that I need to be aware of to test ?

**Comment by BcGovNeal** [comment]
> Are there any setup instructions for this that I need to be aware of to test ?

@nileshnad Since this PR is just for CMS and staff portal won't integrate with it until later, the testing process is a bit manual.

Basically what you need to do is to obtain a Keycloak `access` token with the valid `submitter` or `approver` roles on it.  Then attempt to create or update a resources in CMS with the `access` token in the `Authorization` header.

The simplest way to get the 'access' token is to log into the DEV staff portal and open the `Network` tab.  Look for the request called `token` (https://dev.oidc.gov.bc.ca/auth/realms/g7v0xlf4/protocol/openid-connect/token).  The response of this request will contain the access token.

To figure out what request payload to send, I would just open a park in `Activities & Facilities` and then flip any of the toggle switches.  You should see a `PUT` request sent to an URL similar to `https://api-61d198-dev.apps.silver.devops.gov.bc.ca/api/update/park-activities/678`.  The equivalent CMS URL for this request would be `http://localhost:1337/park-activities/678`.  

Now you have the `access` token, CMS request URL, and request payload.  You just need to create the request in Postman or similar.  If you get 200 status then it worked.  You can verify the value is changed in the CMS admin.

You can also verify CMS is checking the token by changing your roles in Keycloak or send an invalid token.

**Review by nileshnad — COMMENTED** [review]
when I tried to test this out I get the following 

{
"statusCode": 401,
"error": "Unauthorized",
"message": "Cannot read property 'header' of null"
}

**Comment by BcGovNeal** [comment]
> when I tried to test this out I get the following
> 
> { "statusCode": 401, "error": "Unauthorized", "message": "Cannot read property 'header' of null" }

@nileshnad What does your request look like?

**Comment by nileshnad** [comment]
> > when I tried to test this out I get the following
> > { "statusCode": 401, "error": "Unauthorized", "message": "Cannot read property 'header' of null" }
> 
> @nileshnad What does your request look like?

this is the request 

PUT /park-activities/678 HTTP/1.1
HOST: localhost:1337
content-type: application/json
authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJyU0xYRDlaaWJ6ZXdqcEdDekJxcEdzRWxCczhkWXNGdHZ3b085MVh4UXhzIn0.eyJleHAiOjE2MzI4Mzc3OTUsImlhdCI6MTYzMjgwMTc5NywiYXV0aF90aW1lIjoxNjMyODAxNzk1LCJqdGkiOiI3NTU3Njk1Yy1jOTYxLTQ0OTMtOTM4Mi1iZTFjNDRkODQ2MjUiLCJpc3MiOiJodHRwczovL2Rldi5vaWRjLmdvdi5iYy5jYS9hdXRoL3JlYWxtcy9nN3YweGxmNCIsInN1YiI6IjRiZTYwYTk2LTZmMTktNDhhNi1iNTk3LTRlM2E0MGQzZmMwOCIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFjY291bnQiLCJub25jZSI6IjJkMzRiNzc3LWJmMGEtNDk5My04Yjc0LTU3YjYxY2VmNTJiYyIsInNlc3Npb25fc3RhdGUiOiI0OTBhMWJmNC1kNmY3LTQ5OTEtYjMzMy03MzYyYTdlM2YxMzciLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly9sb2NhbGhvc3Q6ODA4MCIsImh0dHBzOi8vYmNwYXJrcy1hZG1pbi02MWQxOTgtZGV2LmFwcHMuc2lsdmVyLmRldm9wcy5nb3YuYmMuY2EiLCJodHRwczovL2Rldi1zdGFmZi5iY3BhcmtzLmNhIiwiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiaHR0cHM6Ly90ZXN0LXN0YWZmLmJjcGFya3MuY2EiXSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJhcHByb3ZlciIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6Ik5pbGVzaCBOYWRrYXJuaSIsInByZWZlcnJlZF91c2VybmFtZSI6Im5hbmFka2FyQGlkaXIiLCJnaXZlbl9uYW1lIjoiTmlsZXNoIiwiZmFtaWx5X25hbWUiOiJOYWRrYXJuaSIsImVtYWlsIjoibmlsZXNoLjEubmFka2FybmlAZ292LmJjLmNhIn0.AjljjB3TYKW6GP9BMIHlQH1GQvnYa6Rnb3NlT2MQZ4w8Yh3tJGhjXylIBe6GapvOcXIRX0w_NRZ_tyggU5AD9oDzuSeiPrfS_U3mZWGDTaeg4iJAjcl6ukZgJH7XWMEeFlExO6n4mN50fCSHg60lltWrYj4irlANq3IJzNv9KoXKnyA7CNbJifd-jHGOHOrFABhLzBbkCJ0EVO1sq8gfxcOuo-hGMXsYSjr4eIJRP4XhojlvxhSjdLMif2Uzb2bkFNuctVnPhs2ldyL_D3i2gXnOcRkEsqnIRhtxbOFhGiuuheRg0J4ZmqfB3hQ1KVlQZ24n1dA_vK0FPIhwxKem_g","expires_in":35998,"refresh_expires_in":1800,"refresh_token":"eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI0MDFmOThhMC03NGQ0LTQ0OWItYjUxZS1kNDA2ODA4ZmJmNmIifQ.eyJleHAiOjE2MzI4MDM1OTcsImlhdCI6MTYzMjgwMTc5NywianRpIjoiOGViMWM2NjYtNWI5Ny00NTNlLThjMDUtMDYzYjM4ODdiNzQyIiwiaXNzIjoiaHR0cHM6Ly9kZXYub2lkYy5nb3YuYmMuY2EvYXV0aC9yZWFsbXMvZzd2MHhsZjQiLCJhdWQiOiJodHRwczovL2Rldi5vaWRjLmdvdi5iYy5jYS9hdXRoL3JlYWxtcy9nN3YweGxmNCIsInN1YiI6IjRiZTYwYTk2LTZmMTktNDhhNi1iNTk3LTRlM2E0MGQzZmMwOCIsInR5cCI6IlJlZnJlc2giLCJhenAiOiJhY2NvdW50Iiwibm9uY2UiOiIyZDM0Yjc3Ny1iZjBhLTQ5OTMtOGI3NC01N2I2MWNlZjUyYmMiLCJzZXNzaW9uX3N0YXRlIjoiNDkwYTFiZjQtZDZmNy00OTkxLWIzMzMtNzM2MmE3ZTNmMTM3Iiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.NwfE1k1WB2rAlkEkOGT4P2830k-SXUDfX2hDYZxq8AQ","token_type":"bearer","id_token":"eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJyU0xYRDlaaWJ6ZXdqcEdDekJxcEdzRWxCczhkWXNGdHZ3b085MVh4UXhzIn0.eyJleHAiOjE2MzI4Mzc3OTUsImlhdCI6MTYzMjgwMTc5NywiYXV0aF90aW1lIjoxNjMyODAxNzk1LCJqdGkiOiIzMDBkMWJkZC1kZmJiLTQzYTMtOWI0Yy0yYWFhN2UyYjljYjYiLCJpc3MiOiJodHRwczovL2Rldi5vaWRjLmdvdi5iYy5jYS9hdXRoL3JlYWxtcy9nN3YweGxmNCIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiI0YmU2MGE5Ni02ZjE5LTQ4YTYtYjU5Ny00ZTNhNDBkM2ZjMDgiLCJ0eXAiOiJJRCIsImF6cCI6ImFjY291bnQiLCJub25jZSI6IjJkMzRiNzc3LWJmMGEtNDk5My04Yjc0LTU3YjYxY2VmNTJiYyIsInNlc3Npb25fc3RhdGUiOiI0OTBhMWJmNC1kNmY3LTQ5OTEtYjMzMy03MzYyYTdlM2YxMzciLCJhY3IiOiIxIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiTmlsZXNoIE5hZGthcm5pIiwicHJlZmVycmVkX3VzZXJuYW1lIjoibmFuYWRrYXJAaWRpciIsImdpdmVuX25hbWUiOiJOaWxlc2giLCJmYW1pbHlfbmFtZSI6Ik5hZGthcm5pIiwiZW1haWwiOiJuaWxlc2guMS5uYWRrYXJuaUBnb3YuYmMuY2EifQ.ZWWv3gIhMeoVWGOc6weX1a5A3AkNJJuMfxikDDL1qwNVPCq8YDf0tEc5pNuAzH6LvIFMXYptKIVJxl58xpPKFMhySHHH-tb9ibAEvwAJxLpjucbUdaBrMYd8E-lTVMB7LInjeSVsMjOrRvcpq2tbzl7u_Q6MHK8CBDmm1eRbBQBKxad-6jhZ5oynbhw4-tr9QGzEjCli_KUg4fjZVt3rPhNY50NlANVeduOycYITmV_4a6kfWObeBug2UyjqyS0BkMu2BIRcDzbdqEkYuUYo_d-v41c2R8SQeSQK6z7Py2A2hxxRnMpnUIRjxbxws8rpZCjy46l1jpCDkdEKGxq65w
content-length: 23

{
  "totalArea":260
}

**Review by nileshnad — APPROVED** [review]
All good to go

**Review by BcGovNeal — APPROVED** [review]

**Pull request merged**
