### PR TITLE
Added Arcgis map to park pages with map center and zoom

### PR DESCRIPTION
**Pull request by siva-ka**
# Description

This PR includes the following proposed change(s):

- BC-484

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Does the change impact or break the Docker build?

- [ ] Yes
- [x] No

If Yes: Has Docker been updated accordingly?

- [ ] Yes
- [ ] No

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by nileshnad — APPROVED** [review]
looks good

**Comment by BcGovNeal** [comment]
@siva-ka I'm unable to get any of the park pages to load to review this PR.  It could be a data issue as I'm using the dev CMS.  Could you please have a look?

**Comment by siva-ka** [comment]
> @siva-ka I'm unable to get any of the park pages to load to review this PR. It could be a data issue as I'm using the dev CMS. Could you please have a look?

@BcGovNeal Are you getting any errors? I use the dev cms as well and I dont face any issues. Could you give me more details?

**Review by BcGovNeal — APPROVED** [review]
Looks good!

**Pull request merged**
